version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: angularclient # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - /vagrant/data/docker-mean/angularclient:/usr/src/app

  express: #name of the second service
    restart: always
    ports:
      - "3000:3000" #specify ports forewarding
    volumes:
      - /vagrant/data/docker-mean/expserver:/usr/src/app
    links:
      - database
    build: expserver # specify the directory of the Dockerfile

  database: # name of the third service
    build: mongo
    ports:
      - "27017:27017" # specify port forewarding
    volumes:
      - /home/vagrant/docker-mean-db:/data/db
